//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Gwt.ServiceSCYWZH {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSCYWZH.ServiceSCYWZHSoap")]
    public interface ServiceSCYWZHSoap {
        
        // CODEGEN: 消息 SubmitPlanTaskRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitPlanTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse SubmitPlanTask(M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitPlanTask", ReplyAction="*")]
        System.Threading.Tasks.Task<M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse> SubmitPlanTaskAsync(M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PackageOfDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string exceptionField;
        
        private System.Data.DataSet valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPlanTask", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitPlanTaskRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public M_Gwt.ServiceSCYWZH.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string receiverId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string senderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string appName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string param;
        
        public SubmitPlanTaskRequest() {
        }
        
        public SubmitPlanTaskRequest(M_Gwt.ServiceSCYWZH.AuthHeader AuthHeader, string receiverId, string senderId, string appName, string title, string message, string param) {
            this.AuthHeader = AuthHeader;
            this.receiverId = receiverId;
            this.senderId = senderId;
            this.appName = appName;
            this.title = title;
            this.message = message;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPlanTaskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitPlanTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public M_Gwt.ServiceSCYWZH.PackageOfDataSet SubmitPlanTaskResult;
        
        public SubmitPlanTaskResponse() {
        }
        
        public SubmitPlanTaskResponse(M_Gwt.ServiceSCYWZH.PackageOfDataSet SubmitPlanTaskResult) {
            this.SubmitPlanTaskResult = SubmitPlanTaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSCYWZHSoapChannel : M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSCYWZHSoapClient : System.ServiceModel.ClientBase<M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap>, M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap {
        
        public ServiceSCYWZHSoapClient() {
        }
        
        public ServiceSCYWZHSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSCYWZHSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSCYWZHSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSCYWZHSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap.SubmitPlanTask(M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest request) {
            return base.Channel.SubmitPlanTask(request);
        }
        
        public M_Gwt.ServiceSCYWZH.PackageOfDataSet SubmitPlanTask(M_Gwt.ServiceSCYWZH.AuthHeader AuthHeader, string receiverId, string senderId, string appName, string title, string message, string param) {
            M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest inValue = new M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.receiverId = receiverId;
            inValue.senderId = senderId;
            inValue.appName = appName;
            inValue.title = title;
            inValue.message = message;
            inValue.param = param;
            M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse retVal = ((M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap)(this)).SubmitPlanTask(inValue);
            return retVal.SubmitPlanTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse> M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap.SubmitPlanTaskAsync(M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest request) {
            return base.Channel.SubmitPlanTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<M_Gwt.ServiceSCYWZH.SubmitPlanTaskResponse> SubmitPlanTaskAsync(M_Gwt.ServiceSCYWZH.AuthHeader AuthHeader, string receiverId, string senderId, string appName, string title, string message, string param) {
            M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest inValue = new M_Gwt.ServiceSCYWZH.SubmitPlanTaskRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.receiverId = receiverId;
            inValue.senderId = senderId;
            inValue.appName = appName;
            inValue.title = title;
            inValue.message = message;
            inValue.param = param;
            return ((M_Gwt.ServiceSCYWZH.ServiceSCYWZHSoap)(this)).SubmitPlanTaskAsync(inValue);
        }
    }
}
