//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Gwt.ServiceECommerce {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceECommerce.ServiceECommerceSoap")]
    public interface ServiceECommerceSoap {
        
        // CODEGEN: 消息 UpdateMaterialsPurchasingRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMaterialsPurchasing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse UpdateMaterialsPurchasing(M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMaterialsPurchasing", ReplyAction="*")]
        System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse> UpdateMaterialsPurchasingAsync(M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest request);
        
        // CODEGEN: 消息 UpdatePurchasingOrderDetailRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchasingOrderDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse UpdatePurchasingOrderDetail(M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchasingOrderDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse> UpdatePurchasingOrderDetailAsync(M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PackageOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccessField;
        
        private string exceptionField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("Exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMaterialsPurchasing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMaterialsPurchasingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public M_Gwt.ServiceECommerce.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strPurchaseOrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strGoodsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int strActualGoodsNum;
        
        public UpdateMaterialsPurchasingRequest() {
        }
        
        public UpdateMaterialsPurchasingRequest(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, int strActualGoodsNum) {
            this.AuthHeader = AuthHeader;
            this.strPurchaseOrderId = strPurchaseOrderId;
            this.strGoodsId = strGoodsId;
            this.strActualGoodsNum = strActualGoodsNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMaterialsPurchasingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMaterialsPurchasingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public M_Gwt.ServiceECommerce.PackageOfBoolean UpdateMaterialsPurchasingResult;
        
        public UpdateMaterialsPurchasingResponse() {
        }
        
        public UpdateMaterialsPurchasingResponse(M_Gwt.ServiceECommerce.PackageOfBoolean UpdateMaterialsPurchasingResult) {
            this.UpdateMaterialsPurchasingResult = UpdateMaterialsPurchasingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePurchasingOrderDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePurchasingOrderDetailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public M_Gwt.ServiceECommerce.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strPurchaseOrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strGoodsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strOrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strOrderState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int strNum;
        
        public UpdatePurchasingOrderDetailRequest() {
        }
        
        public UpdatePurchasingOrderDetailRequest(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, string strOrderId, string strOrderState, int strNum) {
            this.AuthHeader = AuthHeader;
            this.strPurchaseOrderId = strPurchaseOrderId;
            this.strGoodsId = strGoodsId;
            this.strOrderId = strOrderId;
            this.strOrderState = strOrderState;
            this.strNum = strNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePurchasingOrderDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePurchasingOrderDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public M_Gwt.ServiceECommerce.PackageOfBoolean UpdatePurchasingOrderDetailResult;
        
        public UpdatePurchasingOrderDetailResponse() {
        }
        
        public UpdatePurchasingOrderDetailResponse(M_Gwt.ServiceECommerce.PackageOfBoolean UpdatePurchasingOrderDetailResult) {
            this.UpdatePurchasingOrderDetailResult = UpdatePurchasingOrderDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceECommerceSoapChannel : M_Gwt.ServiceECommerce.ServiceECommerceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceECommerceSoapClient : System.ServiceModel.ClientBase<M_Gwt.ServiceECommerce.ServiceECommerceSoap>, M_Gwt.ServiceECommerce.ServiceECommerceSoap {
        
        public ServiceECommerceSoapClient() {
        }
        
        public ServiceECommerceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceECommerceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceECommerceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceECommerceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse M_Gwt.ServiceECommerce.ServiceECommerceSoap.UpdateMaterialsPurchasing(M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest request) {
            return base.Channel.UpdateMaterialsPurchasing(request);
        }
        
        public M_Gwt.ServiceECommerce.PackageOfBoolean UpdateMaterialsPurchasing(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, int strActualGoodsNum) {
            M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest inValue = new M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.strPurchaseOrderId = strPurchaseOrderId;
            inValue.strGoodsId = strGoodsId;
            inValue.strActualGoodsNum = strActualGoodsNum;
            M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse retVal = ((M_Gwt.ServiceECommerce.ServiceECommerceSoap)(this)).UpdateMaterialsPurchasing(inValue);
            return retVal.UpdateMaterialsPurchasingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse> M_Gwt.ServiceECommerce.ServiceECommerceSoap.UpdateMaterialsPurchasingAsync(M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest request) {
            return base.Channel.UpdateMaterialsPurchasingAsync(request);
        }
        
        public System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingResponse> UpdateMaterialsPurchasingAsync(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, int strActualGoodsNum) {
            M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest inValue = new M_Gwt.ServiceECommerce.UpdateMaterialsPurchasingRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.strPurchaseOrderId = strPurchaseOrderId;
            inValue.strGoodsId = strGoodsId;
            inValue.strActualGoodsNum = strActualGoodsNum;
            return ((M_Gwt.ServiceECommerce.ServiceECommerceSoap)(this)).UpdateMaterialsPurchasingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse M_Gwt.ServiceECommerce.ServiceECommerceSoap.UpdatePurchasingOrderDetail(M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest request) {
            return base.Channel.UpdatePurchasingOrderDetail(request);
        }
        
        public M_Gwt.ServiceECommerce.PackageOfBoolean UpdatePurchasingOrderDetail(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, string strOrderId, string strOrderState, int strNum) {
            M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest inValue = new M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.strPurchaseOrderId = strPurchaseOrderId;
            inValue.strGoodsId = strGoodsId;
            inValue.strOrderId = strOrderId;
            inValue.strOrderState = strOrderState;
            inValue.strNum = strNum;
            M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse retVal = ((M_Gwt.ServiceECommerce.ServiceECommerceSoap)(this)).UpdatePurchasingOrderDetail(inValue);
            return retVal.UpdatePurchasingOrderDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse> M_Gwt.ServiceECommerce.ServiceECommerceSoap.UpdatePurchasingOrderDetailAsync(M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest request) {
            return base.Channel.UpdatePurchasingOrderDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailResponse> UpdatePurchasingOrderDetailAsync(M_Gwt.ServiceECommerce.AuthHeader AuthHeader, string strPurchaseOrderId, string strGoodsId, string strOrderId, string strOrderState, int strNum) {
            M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest inValue = new M_Gwt.ServiceECommerce.UpdatePurchasingOrderDetailRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.strPurchaseOrderId = strPurchaseOrderId;
            inValue.strGoodsId = strGoodsId;
            inValue.strOrderId = strOrderId;
            inValue.strOrderState = strOrderState;
            inValue.strNum = strNum;
            return ((M_Gwt.ServiceECommerce.ServiceECommerceSoap)(this)).UpdatePurchasingOrderDetailAsync(inValue);
        }
    }
}
